name: Release to NPM

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build

      - name: Get release tag
        id: get_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: |
          if [[ "${{ steps.get_tag.outputs.RELEASE_TAG }}" == *"-beta"* ]]; then
            npm publish --tag beta --provenance
          elif [[ "${{ steps.get_tag.outputs.RELEASE_TAG }}" == *"-alpha"* ]]; then
            npm publish --tag alpha --provenance
          else
            npm publish --provenance
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
