name: Release to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        type: choice
        options:
          - regular
          - beta
          - alpha

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build

      - name: Get release info
        id: release_info
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            RELEASE_TAG=${GITHUB_REF#refs/tags/}
            echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
            if [[ "$RELEASE_TAG" == *"-beta"* ]]; then
              echo "RELEASE_TYPE=beta" >> $GITHUB_OUTPUT
            elif [[ "$RELEASE_TAG" == *"-alpha"* ]]; then
              echo "RELEASE_TYPE=alpha" >> $GITHUB_OUTPUT
            else
              echo "RELEASE_TYPE=regular" >> $GITHUB_OUTPUT
            fi
          else
            echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: |
          if [ "${{ steps.release_info.outputs.RELEASE_TYPE }}" = "beta" ]; then
            npm publish --tag beta --provenance
          elif [ "${{ steps.release_info.outputs.RELEASE_TYPE }}" = "alpha" ]; then
            npm publish --tag alpha --provenance
          else
            npm publish --provenance
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
